language: node_js
dist: focal
node_js: 16
before_install:
  # install dependencies
  - travis_retry sudo apt-get update -qq
  # install libxml2-utils which contains xmllint that we will use to validate XML against schema)
  - travis_retry sudo apt-get install libxml2-utils
  - npm install -g pkp-plugin-cli

script:
  - xmllint --schema http://pkp.sfu.ca/ojs/xml/plugins.xsd ./plugins.xml --noout
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'main' ]]; then pkp-plugin validate-all-releases --input $TRAVIS_BUILD_DIR/plugins.xml; fi
  - if [ $TRAVIS_PULL_REQUEST != 'false' ]; then pkp-plugin validate-new-release; fi
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'main' ]]; then GITHUB_TOKEN=$GITHUB_TOKEN pkp-plugin generate-site $TRAVIS_BUILD_DIR/plugins.xml; fi

